### ISSUE TITLE
Add ability to set tracker php endpoint and js script

### ISSUE THREAD

**Issue by zachrank** [pzmosquito/matomo-router5-plugin#5]
Matomo now instructs users with `matomo.php` and `matomo.js` rather than `piwik.php` or `piwik.js` when providing tracking code but both are available to use. It doesn't appear that `piwik.php` or `piwik.js` are going away anytime soon but it would be nice to be able to choose which endpoint/script this plugin uses if one was preferred over the other.

Reference:
piwik.php still contains all of the tracking code logic: https://github.com/matomo-org/matomo/blob/fd14a155269038f6fe12ce31db20f8ebffaf00c5/piwik.php
matomo.php simply includes piwik.php: https://github.com/matomo-org/matomo/blob/fd14a155269038f6fe12ce31db20f8ebffaf00c5/matomo.php

**Comment by pzmosquito** [comment]
thanks Zach, I'll add the support

**Comment by pzmosquito** [comment]
[0.4.0](https://github.com/pzmosquito/matomo-router5-plugin/releases/tag/0.4.0) is released
